@echo off
REM Generate Python and C++ Protobuf/gRPC stubs
echo ============================================
echo Generating Protobuf/gRPC Stubs
echo ============================================

REM Check if protoc is available
where protoc >nul 2>nul
if %errorlevel% neq 0 (
    echo [ERROR] 'protoc' not found in PATH. Please install Protocol Buffers compiler.
    echo Download from: https://github.com/protocolbuffers/protobuf/releases
    exit /b 1
)

echo [1/3] Generating Python stubs...
python -m grpc_tools.protoc ^
    -I./protos ^
    --python_out=../src/backtesting ^
    --grpc_python_out=../src/backtesting ^
    ./protos/backtest.proto

if %errorlevel% neq 0 (
    echo [ERROR] Failed to generate Python stubs
    exit /b %errorlevel%
)
echo ✓ Python stubs generated

echo [2/3] Generating C++ stubs (for IntelliSense and manual builds)...
REM Note: CMake will regenerate these, but we can create them here for IDE support
if not exist build mkdir build
protoc ^
    -I./protos ^
    --cpp_out=./build ^
    --grpc_out=./build ^
    --plugin=protoc-gen-grpc="C:/Program Files (x86)/grpc/bin/grpc_cpp_plugin.exe" ^
    ./protos/backtest.proto

if %errorlevel% neq 0 (
    echo [WARNING] C++ stub generation failed. CMake will handle this during build.
    echo Ensure grpc_cpp_plugin is in PATH or CMake has gRPC configured.
)
echo ✓ C++ stubs will be generated by CMake

echo [3/3] All done!
echo ============================================
echo You can now run build_cpp.bat to compile the C++ engine
echo ============================================
