# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: backtest.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'backtest.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62\x61\x63ktest.proto\x12\x0c\x61lpha_engine\"`\n\x03\x42\x61r\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\r\n\x05\x63lose\x18\x05 \x01(\x01\x12\x0e\n\x06volume\x18\x06 \x01(\x01\"\xe2\x01\n\x0eStrategyConfig\x12\x13\n\x0bstrategy_id\x18\x01 \x01(\t\x12@\n\nparameters\x18\x02 \x03(\x0b\x32,.alpha_engine.StrategyConfig.ParametersEntry\x12\x17\n\x0finitial_capital\x18\x03 \x01(\x01\x12\x17\n\x0f\x63ommission_rate\x18\x04 \x01(\x01\x12\x14\n\x0cslippage_bps\x18\x05 \x01(\x01\x1a\x31\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"p\n\x0f\x42\x61\x63ktestRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x1f\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x11.alpha_engine.Bar\x12,\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x1c.alpha_engine.StrategyConfig\"f\n\x05Trade\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x10\n\x08quantity\x18\x05 \x01(\x01\x12\x0b\n\x03pnl\x18\x06 \x01(\x01\"0\n\x0b\x45quityPoint\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0e\n\x06\x65quity\x18\x02 \x01(\x01\"\x84\x02\n\x10\x42\x61\x63ktestResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12#\n\x06trades\x18\x04 \x03(\x0b\x32\x13.alpha_engine.Trade\x12/\n\x0c\x65quity_curve\x18\x05 \x03(\x0b\x32\x19.alpha_engine.EquityPoint\x12\x14\n\x0ctotal_return\x18\x06 \x01(\x01\x12\x14\n\x0csharpe_ratio\x18\x07 \x01(\x01\x12\x14\n\x0cmax_drawdown\x18\x08 \x01(\x01\x12\x10\n\x08win_rate\x18\t \x01(\x01\x12\x14\n\x0ctotal_trades\x18\n \x01(\x05\x32\x61\n\x0f\x42\x61\x63ktestService\x12N\n\x0bRunBacktest\x12\x1d.alpha_engine.BacktestRequest\x1a\x1e.alpha_engine.BacktestResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'backtest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STRATEGYCONFIG_PARAMETERSENTRY']._loaded_options = None
  _globals['_STRATEGYCONFIG_PARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_BAR']._serialized_start=32
  _globals['_BAR']._serialized_end=128
  _globals['_STRATEGYCONFIG']._serialized_start=131
  _globals['_STRATEGYCONFIG']._serialized_end=357
  _globals['_STRATEGYCONFIG_PARAMETERSENTRY']._serialized_start=308
  _globals['_STRATEGYCONFIG_PARAMETERSENTRY']._serialized_end=357
  _globals['_BACKTESTREQUEST']._serialized_start=359
  _globals['_BACKTESTREQUEST']._serialized_end=471
  _globals['_TRADE']._serialized_start=473
  _globals['_TRADE']._serialized_end=575
  _globals['_EQUITYPOINT']._serialized_start=577
  _globals['_EQUITYPOINT']._serialized_end=625
  _globals['_BACKTESTRESPONSE']._serialized_start=628
  _globals['_BACKTESTRESPONSE']._serialized_end=888
  _globals['_BACKTESTSERVICE']._serialized_start=890
  _globals['_BACKTESTSERVICE']._serialized_end=987
# @@protoc_insertion_point(module_scope)
